   ORG 100

start:
        
MOV WORD PTR [0120h],5678H  ;Carpanin 16-0 bitini bellege yerlestirdim
MOV WORD PTR [0122h],1234H   ;Carpanin 32-16 bitini bellege yerlestirdim
MOV WORD PTR [0124h],5678H   ;Carpilanin 16-0 bitini bellege yerlestirdim
MOV WORD PTR [0126h],1234H   ;Carpilanin 32-16 bitini bellege yerlestirdim

MOV WORD PTR [0130h],0000h  ;CARPIMIN 16-0  arasinin bellek adresi
MOV WORD PTR [0132h],0000h  ;CARPIMIN 32-16 arasinin bellek adresi
MOV WORD PTR [0134h],0000h  ;CARPIMIN 48-32 arasinin bellek adresi
MOV WORD PTR [0136h],0000h  ;CARPIMIN 64-48 arasinin bellek adresi

SUB AX,AX
SUB BX,BX
SUB CX,CX
SUB DX,DX
SUB SI,SI
SUB DI,DI


MOV SI,32       ;Dongu sayacimiz Dec olarak 32      

tekrar:

MOV BX,[120h]  ; CARPANIN 16-0 BITINI DIYA AKTAR
AND BX,01H 	; CARPANIN LSB'SI DISINDA DIGER BITLERI 0LA ANDLE YANI 0 YAP (LSBYI 1 LE ANDLE YANI LSB ONCEDEN NEYSE SONRADAN DA O OLACAK)
XOR BX,01H	; CARPANIN LSB BITI 0 MI DIYE KONTROL ET 0 SA ZERO FLAG 0  A ESITLENIR
JZ topla_kaydir ; CARPANIN LSB BITI 1 ISE ZERO FLAG 1 E ESITLENIR VE JZ DEKI FONKSIYONA GIT
CLC	; CARPANIN LSB BITI 1 DEGILDIR ZERO FLAG 0 DIR CARRYI TEMIZLE


devam:

MOV AX,[0136h]
RCR AX,1        ;CARPIM SONUCUNUN 64-48 BITINI BIR SAGA KAYDIR
MOV [0136h],AX
MOV BX,[0134h]      
RCR BX,1        ;CARPIM SONUCUNUN 48-32 BITINI BIR SAGA KAYDIR
MOV [0134h],BX
MOV CX,[0132h]
RCR CX,1        ;CARPIM SONUCUNUN 32-16 BITINI BIR SAGA KAYDIR
MOV [0132h],CX	
MOV DX,[0130h]
RCR DX,1        ;CARPIM SONUCUNUN 16-0  BITINI BIR SAGA KAYDIR
MOV [0130h],DX	  
MOV AX,[0122h]
SHR AX,1        ;CARPANI BIR BIT SAGA KAYDIR
MOV [0122h],AX 
MOV BX,[0120h]
RCR BX,1        ;CARPANI BIR BIT SAGA KAYDIR AMA CARRY ILE BIRLIKTE GELIRSE YANI CARPANIN 32-16 BITINDEN GELEN ELDEYI DE KULLANARAK
MOV [0120h],BX 
   		
DEC SI		;DONGU DEGISKENINI AZALT
CMP SI,0	;DEGISKEN 0 MI DIYE BAK	
JNZ tekrar	;SIFIR DEGI, KONTROLCUYE GIT
JMP son		;UYGULAMAYI BITIRMEYE GIT 


topla_kaydir: 

MOV DX,[0124h]	;DX'E CARPILANIN 16-0 BITINI KOPYALA
ADD [0134h],DX  ;CARPIMIN 48-32 BITINE BURADA CARRY ONEMLI DEGIL
MOV DX,[0126h]  ;DX'E CARPILANIN 32-16 BITINI KOPYALA
ADC [0136h],DX  ;CARPIMIN 64-48 BITINE CARRY I GOZ ONUNE ALARAK ATA
JMP devam  


son:

HLT		;SONUCLAR MSB DEN LSB YE 0136H-0130H BELLEK GOZLERINDE TUTULMAKTADIR